### ISSUE TITLE
autoplay turns on as soon as one has interacted with the slider.

### ISSUE THREAD

**Issue by zehawki** [YIZHUANG/react-multi-carousel#326] opened 2022-02-27 15:16 UTC
**Describe the bug**
Issue with AutoPlay. 
If autoplay prop has NOT been set, or even explicitly set to false, autoplay turns on as soon as one has interacted with the slider.

However setting `shouldResetAutoplay={false}` _turns this behavior off._
Its extremely unintuitive that "automatic" autoplay can be turned off by setting `shouldResetAutoplay={false}`. I discovered this only with various trials.

**Expected behavior**
When autoPlay is off, it should be off, irrespective of interactions with the slider.

**Version**
v2.8.0

**Comment by jtas01** [comment] 2022-03-02 12:48
Same is happening with me too.

**Comment by zehawki** [comment] 2022-03-02 23:13
Actually now I'm quite puzzled as to what this prop is supposed to do.

With `autoPlay` and `shouldResetAutoplay` both set to true, I expected that the autoplay will STOP (ie get reset as the prop name says) as soon as one has interacted with the slider. But setting `shouldResetAutoplay` to true or false seems to be having no effect.

**Comment by hackntest** [comment] 2022-03-08 17:04
Having the same issue

**Comment by djordjejanjic** [comment] 2022-04-04 15:37
Did anyone solve this? I have trouble with this bug also

**Comment by alitursucular** [comment] 2022-04-04 16:24
Definitely not a solution, but a workaround I ended up with is to set `autoPlaySpeed={10000000}`.

**Comment by jtas01** [comment] 2022-04-05 07:22
> Definitely not a solution, but a workaround I ended up with is to set `autoPlaySpeed={10000000}`.

This made me lol.... nice workaround. But definitely need a real solution soon.

**Comment by djordjejanjic** [comment] 2022-04-05 08:15
I just tried with shouldResetAutoplay = false and autoplay = false. It works!

**Comment by trinhtuan2801** [comment] 2022-04-05 11:18
> shouldResetAutoplay

it works for me <3

**Comment by trinhtuan2801** [comment] 2022-04-05 11:19
> 



> shouldResetAutoplay = false and autoplay = false

it works for me 💯

**Comment by sandeepDevJs** [comment] 2022-04-23 09:49
> I just tried with shouldResetAutoplay = false and autoplay = false. It works!

This worked for me. thanks dude.

**Comment by zehawki** [comment] 2022-04-23 10:35
>I just tried with shouldResetAutoplay = false and autoplay = false. It works! 

@djordjejanjic Isnt that exactly what I said in the first post? :-)

**Comment by djaffer** [comment] 2022-04-24 08:58
same issue. Just saved the hassle.

> I just tried with shouldResetAutoplay = false and autoplay = false. It works!

thank you! @djordjejanjic

**Comment by YIZHUANG** [comment] 2022-06-14 22:24
This was a bug caused by one of the PRs, should be fixed now in the latest version

**Comment by YIZHUANG** [comment] 2022-06-14 22:24
This was a bug caused by one of the PRs, should be fixed now in the latest version

**Closed by YIZHUANG** 2022-06-14 22:24 UTC
