### ISSUE TITLE
Carousel breaks if there are not enough items to fill a slide and dots are set to show

### ISSUE THREAD

**Issue by tomhicklingnc** [YIZHUANG/react-multi-carousel#106] opened 2019-11-18 13:32 UTC
We've found that the carousel errors with the following message if you have dots set to show, but if there are not enough items to fill a full slide:
```
RangeError: Invalid array length
    at Object.e.getLookupTableForNextSlides (VM162 vendors~FeaturedProductsRoot-c10d59730b75f0d49ae7.js:12)
    at e.default (VM162 vendors~FeaturedProductsRoot-c10d59730b75f0d49ae7.js:12)
```
Our code looks something like the following:
```
  const settings = {
    desktop: {
      breakpoint: { min: 1440, max: 3000 },
      items: 5,
    },
  };
  return (
    <Carousel
      responsive={settings}
      arrows={false}
      showDots
      swipeable
      draggable
      beforeChange={() => setIsMoving(true)}
      afterChange={() => setIsMoving(false)}
    >
      // Slide rendering logic, when fewer slides are present here than the number defined above we experience the problem.
    </Carousel>
  );
```

This issue is fixed if we disable dots, but we need them in order to convey to the user that the interface is a carousel.

**Comment by YIZHUANG** [comment] 2019-11-18 13:38
Have you tried the latest version?

**Comment by tomhicklingnc** [comment] 2019-11-18 13:39
We've tried this in 2.4.1 yes.

**Comment by YIZHUANG** [comment] 2019-11-18 13:53
@tomhicklingnc  I couldn't reproduce this, can you put up a reproduction on code sandbox and post it here?

**Comment by tomhicklingnc** [comment] 2019-11-18 14:02
I've found an example of this happening as provided by someone else:
https://codesandbox.io/s/jolly-hooks-yzpqs

**Comment by YIZHUANG** [comment] 2019-11-18 14:27
It's fixed now in 2.4.2 https://github.com/YIZHUANG/react-multi-carousel/pull/107

**Closed by YIZHUANG** 2019-11-18 14:27 UTC

**Comment by TheManFromEarth1** [comment] 2021-02-03 21:23
This same error appears again with 2.6.1.
It happens when items are set at more than available items.

When I set showDots as false, it works.

**Comment by macojaune** [comment] 2022-10-03 18:57
Still hapening on 2.8.2
