### ISSUE TITLE
Does not render with style: display: 'flex'

### ISSUE THREAD

**Issue by riancarlosdev** [YIZHUANG/react-multi-carousel#315] opened 2022-02-07 03:42 UTC
When to use the display: 'flex'. The carousel becomes invisible. to be more exact.... it doesn't render the internal content

https://codesandbox.io/s/xenodochial-field-ltiqb?file=/src/App.js

**Comment by B0rk3** [comment] 2022-02-07 17:49
I think your issue is a duplicate of #98

**Comment by YIZHUANG** [comment] 2022-02-10 21:17
Hello, the parent's width needs to be set to 100

**Closed by YIZHUANG** 2022-02-10 21:17 UTC
