### ISSUE TITLE
Width change of react-multi-carousel-item 

### ISSUE THREAD

**Issue by Aman1kr** [YIZHUANG/react-multi-carousel#145] opened 2020-03-31 18:01 UTC
Can you tell how can i change the width of react-multi-carousel-item 
in style.css whre i need  the code. Actually i want that width of react-multi-carousel-item should be 80%; acc to screen

**Comment by abhinavdalal** [comment] 2020-04-01 04:20
@Aman1kr have you tried using the itemClass prop to pass your custom class with the width: 80%;

itemClass | string | '' | CSS class for carousel item, use this to style your own Carousel item. For example add padding-left and padding-right

pls close this ticket if that fixes your issue

**Comment by Aman1kr** [comment] 2020-04-01 07:55
I have tried this in the css 
.react-multi-carousel-item{
  width:200px!important;
}
but not working 

by doing the inspect element this seems that element inside 
<div class="react-multi-carousel-list  ">
  <ul class="react-multi-carousel-track " style="transition: transform 400ms ease-in-out 0s; overflow: 
  unset; transform: translate3d(0px, 0px, 0px);">
     <li data-index="0" aria-hidden="false" class="react-multi-carousel-item react-multi-carousel- 
      item--active " style="flex: 1 1 auto; position: relative; width:CUSTOM_WIDTH;">
     <div class="set">
     <img class="img-size" src="./assets/id-9-cat-1.jpg" alt="Product 1">
     </div>
     </li>
 </ul>
</div>

**Comment by abhinavdalal** [comment] 2020-04-01 08:12
@Aman1kr I think you need to create a class and pass it down via prop itemClass as I said earlier.. overriding css gets tricky with css specificity and is not a good practice..

**Closed** 2020-04-01 09:12 UTC

**Comment by plumest** [comment] 2021-07-12 05:25
I think I have the same issue. I pass down the class to `itemClass` like this

```css
.itemClass {
    width: 730px !important;
    padding: 0 10px;
}
```

It good at fix the width of my items but the problem is it not at the center (I also add `centerMode={true}`) And it moves randomly every time it slides. I think the problem is `transform: translate3d(someValue, 0px, 0px);`
Do you have some ways to fix the transform value?
PS. I try to add `additionalTransfrom={-575}` this way it makes the first item center but it still broke for others and if I resize it also broke.
